apiVersion: v1
kind: Pod
metadata:
  name: mypod4
spec:
  containers:
  - name: mycontainer4
    image: nginx
    volumeMounts:
    - name: myvolume
      mountPath: /usr/local/apache2/htdocs/
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: mypvc
    ports:
    - containerPort: 80

---
