services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  tomcat-app:
    image: aryanbansode/b20:myhttpd
    ports:
      - "8080:8080"

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  httpd:
    image: aryanbansode/b20:myhttpd
    ports:
      - "81:80"
    volumes:
      - /data:/usr/local/apache2/htdocs/
volumes:
  data:
 


